// src/types/student.ts
export interface Student {
  id: string;
  student_id: string;
  name: string;
  email?: string;
  phone?: string;
  gender?: string;
  date_of_birth?: string;
  faculty_id?: string;
  faculty_code?: string;
  faculty?: string;
  department_id?: string;
  department_code?: string;
  department?: string;
  program_id?: string;
  program?: string;
  current_level_id?: string;
  current_level?: string;
  current_semester_id?: string;
  current_semester?: string;
  academic_session_id?: string;
  academic_session?: string;
  admission_year?: string;
  year_of_entry?: string;
  matric_number?: string;
  program_name?: string;
  level_code?: string;
  level?: string | number;
  semester_number?: number;
  session_year?: string;
  course_codes?: string[];
  photo_url?: string;
  face_enrolled_at?: string;
  face_embedding?: number[];
  face_embedding_vector?: number[];
  face_match_threshold?: number;
  enrollment_status: 'pending' | 'enrolled' | 'verified';
  last_face_scan?: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}